let buildingListMk1 = [
	{id: 0,name: "caserne1", nom:'Caserne niveau 1', price: 200000, income: -5000, ecologie: -5, economie: -3, bienEtre: 5, pop: 0,  description: "La caserne est un bâtiment peu coûteux en entretien et qui consomme peu, mais qui donne un sentiment de sécurité aux citoyens de la ville, car ils se sentent protégés en cas de problème, comme les incendies.",x:0,y:-10, popMin: 200,sizeX: 0,sizeY: 0},
	{id: 1,name : "centrale1", nom:'Centrale électrique niveau 1', price: 575000, income: -15000, ecologie: -10, economie: -7, bienEtre: 9, pop: 0, description: "La centrale électrique est un bâtiment très polluant et très coûteux en entretien, mais qui permet aux habitants d'avoir une ressource indispensable pour une ville moderne: l'électricité.",x:0, y:-30, popMin: 500,sizeX: 0,sizeY: 0},
	{id: 2,name : "commissariat1", nom:'Commissariat niveau 1', price: 200000, income: -5000, ecologie: -5, economie: -2, bienEtre: 5, pop: 0, description: "Le commissariat est un bâtiment peu coûteux en entretien qui donne un sentiment de sécurité à la population.",x:0, y: -10, popMin: 200,sizeX: 0,sizeY: 0},
	{id: 3,name : "ecole1", nom:'Ecole niveau 1', price: 250000, income: -5000, ecologie: -5, economie: -5, bienEtre: 5, pop: 0, description: "L'école est un bâtiment peu coûteux en entretien, qui pollue peu et est indispensable pour le bien-être de la population.",x:30, y:-10, popMin: 100,sizeX: 0,sizeY: 0},
	{id: 4,name	: "hopital1", nom:'Hôpital niveau 1', price : 500000, income: -5000, ecologie: -5, economie: -5, bienEtre: 5, pop: 0, description: "L'hôpital est un bâtiment coûteux en entretien et polluant mais qui reste obligatoire dans une ville se disant intelligente",x:50, y: -50, popMin: 300,sizeX: 0,sizeY: 0},
	{id: 5,name : "poste1", nom:'Poste niveau 1', price: 150000, income: -5000, ecologie: -1, economie: -2, bienEtre: 5, pop: 0, description: "La poste est un bâtiment peu coûteux en entretien et peu polluant qui augmente le bien-être des habitants.",x:0, y: -10, popMin: 100,sizeX: 0,sizeY: 0},
	{id: 6,name	: "centrale_hydraulique1", nom:'Centrale hydraulique niveau 1', price: 950000, income : -35000, ecologie : 15, economie : -15, bienEtre: 0, pop: 0, description: "La centrale hydraulique est un bâtiment très coûteux en entretien mais qui permet de produire de l'électricité de manière renouvelable, elle améliore donc l'écologie.",x: -70, y:-40,sizeX: 1,sizeY: 2, popMin: 500},
	{id: 7,name : "panneau_solaire", nom:'Panneau solaire niveau 1', price: 450000, income: -15000, ecologie: 10, economie: -4, bienEtre: 0, pop: 0, description: "Les panneaux solaires sont assez coûteux en entretien mais permettent de produire de l'électricité de manière renouvelable.",x: 0, y:-100,sizeX: 2,sizeY:2, popMin: 400},
	{id: 8, name: "parc1", nom:'Parc niveau 1', price: 100000, income: -7500, ecologie: 10, economie: -5, bienEtre: 10, pop: 0, description: "Un parc apporte du bien-être et du divertissement à la population, et permet à la ville de respirer augmentant donc l'écologie.", x: 0,y:-10, popMin: 100,sizeX: 0,sizeY: 0},
	{id: 9, name: "usine_recyclage1", nom:'Usine de recyclage niveau 1', price: 750000, income: -25000, ecologie: 15, economie: -15, bienEtre: -15, pop: 0, description: "Une usine de recyclage est un bâtiment très coûteux en entretien mais qui permet de recycler les déchets de la ville.", x: 0,y:-10, popMin: 300,sizeX: 0,sizeY: 0},
	{id: 10, name: "banque1", nom:'Banque niveau 1', price: 850000, income: 75000, ecologie: -10, economie: 15, bienEtre: 3, pop: 0, description: "La banque est un bâtiment coûteux en entretien, mais essentiel quelque soit la ville car elle permet d'augmenter grandement son économie.",x:30, y: -180, popMin: 600,sizeX: 0,sizeY: 0},
	{id: 11, name: "magasin1", nom:'Magasin niveau 1', price: 150000, income: 30000, ecologie: -5, economie: 10, bienEtre: 3, pop: 0, description: "Les magasins permettent à la ville de faire vivre son économie. C'est un peu la base du commerce de chaque ville.",x:0, y: -10, popMin: 100,sizeX: 0,sizeY: 0},
	{id: 12, name: "usine1", nom:'Usine niveau 1', price: 500000, income: 70000, ecologie: -20, economie: 14, bienEtre: -20, pop: 0, description: "L'usine est un bâtiment très polluant et bruyant, mais qui contribue énormément à l'économie de la ville et rapporte beaucoup.", x:20, y: -10, popMin: 100,sizeX: 0,sizeY: 0},
	{id: 13, name: "mairie1", nom:'Mairie niveau 1', price: 0, income: 0, ecologie: 0, economie: 0, bienEtre: 0, pop: 0, description: "La mairie est le bâtiment à partir duquel vous allez pouvoir acheter des avancées technologiques. L'améliorer permet aussi de pouvoir améliorer les autres bâtiments.", x:0,y:-40, popMin: 0,sizeX: 0,sizeY: 0},
	{id: 14, name: "maison1", nom:'Maison niveau 1', price: 100000, income: 10000, ecologie: -3, economie: 3, bienEtre: 2, pop: 100, description: "Les maisons sont essentielles pour avoir des habitants dans la ville. Cependant elles demandent un petit coût en entretien et consomment un peu.",x:0,y:-40, popMin: 0,sizeX: 0,sizeY: 0},
];

let buildingListMk2 = [
	{id: 0,name: "caserne2", nom:'Caserne niveau 2', price: 350000, income: -3000, ecologie: -3, economie: -2, bienEtre: 7, pop: 0, description: "La caserne est un bâtiment peu coûteux en entretien et qui consomme peu, mais qui donne un sentiment de sécurité aux citoyens de la ville, car ils se sentent protégés en cas de problèmes comme les incendies. \r\n La caserne au niveau 2 possède une meilleure isolation avec des coûts d'entretien réduits. Avoir une meilleure caserne des pompiers augmente encore plus le bien-être des habitants.",x:100,y:-100, popMin: 600,sizeX: 0,sizeY: 0},
	{id: 1,name : "centrale2", nom:'Centrale électrique niveau 2', price: 800000, income : -12000, ecologie: -7, economie: -5, bienEtre: 13, pop: 0, description: "La centrale électrique est un bâtiment très polluant et très coûteux en entretien, mais qui permet au habitants d'avoir une ressource indispensable pour une ville moderne: l'électricité. \r\n La centrale au niveau 2 possède de meilleures techniques pour produire de l'électricité, moins polluantes, ce qui augmente donc les revenus et baisse moins l'écologie.",x:-100,y:-65,sizeX:1,sizeY:2, popMin: 1000},
	{id: 2,name : "commissariat2", nom:'Commissariat niveau 2', price: 350000, income: -3000, ecologie: -3, economie: -1, bienEtre: 7, pop: 0, description: "Le commissariat est un bâtiment peu coûteux en entretien qui donne un sentiment de sécurité à la population.\r\n Le commissariat niveau 2 possède une meilleure isolation avec des coûts d'entretien réduits. Avoir un meilleur commissariat augmente encore plus le bien-être des habitants, se sentant plus en sécurité.",x:10,y:-110, popMin :600,sizeX: 2,sizeY: 2},
	{id: 3,name : "ecole2", nom:'Ecole niveau 2', price: 350000, income: -3000, ecologie: -3, economie: -3, bienEtre: 7, pop: 0, description: "L'école est un bâtiment peu coûteux en entretien, qui pollue peu et est indispensable pour le bien être de la population.\r\n L'école au niveau 2 possède une meilleure isolation avec des coûts d'entretien réduits. Avoir une meilleure école augmente encore plus le bien-être des habitants.",x:-100,y:-120,sizeX:1,sizeY:2, popMin: 600},
	{id: 4,name	: "hopital2", nom:'Hôpital niveau 2', price : 350000, income: -3000, ecologie: -3, economie: -3, bienEtre: 7, pop: 0, description: "L'hôpital est un bâtiment coûteux en entretien et polluant mais qui reste obligatoire dans une ville se disant intelligente.\r\n L'hôpital au niveau 2 possède une meilleure isolation avec des coûts d'entretien réduits.Avoir un meilleur hôpital augmente encore plus le bien-être des habitants.",x:45,y:-20, popMin: 600,sizeX: 0,sizeY: 0},
	{id: 5,name : "poste2", nom:'Poste niveau 2', price: 350000, income: -3000, ecologie: -3, economie: -2.5, bienEtre: 10, pop: 0, description: "La poste est un bâtiment peu coûteux en entretien et peu polluant qui augmente le bien-être des habitants.\r\n La poste au niveau 2 possède une meilleure isolation avec des coûts d'entretien réduits.Avoir une meilleure poste augmente encore plus le bien-être des habitants.",x:0,y:-40,sizeX:2,sizeY:1, popMin: 1000},
	{id: 6,name	: "centrale_hydraulique2", nom:'Centrale hydraulique niveau 2', price: 1200000, income : -25000, ecologie : 20, economie : -9, bienEtre: -7, pop: 0, description: "La centrale hydraulique est un bâtiment tres coûteux en entretien mais qui permet produire de l'électricité de manière renouvelable, elle améliore donc beaucoup la statistique d'écologie. \r\n La centrale hydraulique au niveau 2 est moins chère en entretien et permet de produire encore plus d'électricité, toujours de manière renouvelable.",x:30,y:-85,sizeX:2,sizeY:2, popMin: 1200},
	{id: 7,name : "panneau_solaire2", nom:'Panneau solaire niveau 2', price: 900000, income: -10000, ecologie: 15, economie: -2, bienEtre: 0, pop: 0, description: "Les panneaux solaires sont assez coûteux en entretien mais permettent de produire de l'électricité de manière renouvelable. ",x: 0, y:-100,sizeX:2,sizeY:2, popMin: 600},
	{id: 8, name: "parc2",  nom:'Parc niveau 2',price: 250000, income: -8000, ecologie: 15, economie: -8, bienEtre: 15, description: "Un parc apporte du bien-être et du divertissement à la population, et permet à la ville de respirer, ceci favorise donc l'écologie. \r\n Les parcs au niveau 2 sont moins coûteux en entretien et sont plus modernes, augmentant ainsi le bien-être des habitants.",x: 20, y:-110,sizeX:2,sizeY:2, popMin: 600},
	{id: 9, name: "usine_recyclage2", nom:'Usine de recyclage niveau 2', price: 1000000, income: -22500, ecologie: 20, economie: -10, bienEtre: -5, pop: 0, description: "L'usine de recyclage est un bâtiment très coûteux en entretien mais qui permet de recycler les déchets de la ville. \r\n L'usine de recylcage au niveau 2 est moins coûteuse en entretien et permet de recycler plus de déchets par jour.",x:-60,y:-110,sizeX:1,sizeY:2, popMin: 1000},
	{id: 10, name: "banque2", nom:'Banque niveau 2', price: 1250000, income: 125000, ecologie: -7, economie: 25, bienEtre: 7, pop: 0, description: "La banque est un bâtiment coûteux en entretien, mais essentiel quelque soit la ville car elle permet d'augmenter grandement son économie. \r\n La banque au niveau 2 possède une meilleure isolation avec des coûts d'entretien réduits. Avoir une meilleure banque augmente les revenus et l'économie.",x:30, y: -180, popMin: 1200,sizeX: 0,sizeY: 0},
	{id: 11, name: "magasin2", nom:'Magasin niveau 2', price: 250000, income: 45000, ecologie: -5, economie: 18, bienEtre: 8, pop: 0, description: "Les magasins permettent à la ville de faire vivre son économie. C'est un peu la base du commerce de chaque ville. \r\n Les magasins au niveau 2 possèdent une meilleure isolation, augmentent les revenus et l'économie.",x:0,y:-40,sizeX:1,sizeY:2, popMin: 600},
	{id: 12, name: "usine2", nom:'Usine niveau 2', price: 750000, income: 100000, ecologie: -20, economie: 19, bienEtre: -7, pop: 0, description: "L'usine est un bâtiment très polluant et bruyant, mais qui contribue énormément à l'économie de la ville et rapporte beaucoup. \r\n Les usines au niveau 2 polluent moins et produisent plus, augmentant ainsi l'économie et les revenus.",x:-110,y:-90,sizeX:1,sizeY:2, popMin: 600},
	{id: 13, name: "mairie2", nom:'Mairie niveau 2', price: 1500000, income: 0, ecologie: 0, economie: 0, bienEtre: 0, pop: 0, description: "La mairie est le bâtiment à partir duquel vous allez pouvoir acheter des avancées technologiques. \r\n La mairie au niveau 2 permet de débloquer les améliorations des autres bâtiments et des technologies de rang 2.",x:-100,y:-100,sizeX:1,sizeY:2, popMin: 700},
	{id: 14, name: "maison2", nom:'Maison niveau 2', price: 250000, income: 20000, ecologie: -3, economie: 8, bienEtre: 5, pop: 300, description: "Les maisons sont essentielles pour avoir des habitants dans la ville. Cependant elles demandent un petit coût en entretien et consomment un peu. \r\n Les maisons de niveau 2 ont une meilleure isolation et un coût d'entretien plus faible. Elles permettent aussi d'acceuillir plus de personnes.",x:-20,y:-110,sizeX:1,sizeY:2, popMin: 0}
];

let buildingListMk3 = [
	{id: 0,name: "caserne3", nom:'Caserne niveau 3', price: 1000000, income: -1500, ecologie: 5, economie: -1, bienEtre: 14, pop: 0, description: "La caserne est un bâtiment peu coûteux en entretien et qui consomme peu, mais qui donne un sentiment de sécurité aux citoyens de la ville, car ils se sentent protégés en cas de problèmes comme les incendies. \r\n La caserne au niveau 3 possède des camions de pompiers moins polluants, fonctionnant à l'énergie verte. Avoir une meilleure caserne des pompiers augmente plus le bien-être des habitants, se sentant en sécurité.",x:0,y:-50,sizeX:2,sizeY:1, popMin: 1200},
	{id: 1,name : "centrale3", nom:'Centrale électrique niveau 3', price: 2200000, income: -8000, ecologie: -5, economie: -3, bienEtre: 15, pop: 0, description: "La centrale électrique est un bâtiment très polluant et très coûteux en entretien, mais qui permet au habitants d'avoir une ressource indispensable pour une ville moderne: l'électricité. \r\n La centrale au niveau 3 utilise une technologie révolutionnaire et bien moins polluante: la fusion nucléaire ce qui augmente donc beaucoup les revenus et est moins impactant pour l'écologie.",x:10,y:-110,sizeX:2,sizeY:2, popMin: 1500},
	{id: 2,name : "commissariat3", nom:'Commissariat niveau 3', price: 1000000, income: -1500, ecologie: -1, economie: -1, bienEtre: 20, pop: 0, description: "Le commissariat est un bâtiment peu coûteux en entretien qui donne un sentiment de sécurité à la population. \r\n Au commissariat niveau 3, les policiers ont des hélicoptères électriques, moins polluants, permettant d'intervenir plus vite et d'avoir un service plus fiable. Avoir un meilleur commissariat augmente encore plus le bien-être des habitants, se sentant plus en sécurité.",x:20,y:-200,sizeX:2,sizeY:1, popMin :1200},
	{id: 3,name : "ecole3", nom:'Ecole niveau 3', price: 1000000, income: -1500, ecologie: -1, economie: -1, bienEtre: 20, pop: 0, description: "L'école est un bâtiment peu coûteux en entretien, qui pollue peu et est indispensable pour le bien-être de la population. \r\n L'école au niveau 3 a des nouvelles techniques d'enseignement. Avoir une meilleure école augmente encore plus le bien-être des habitants.",x:-20,y:-200,sizeX:1,sizeY:2, popMin: 1200},
	{id: 4,name	: "hopital3", nom:'Hôpital niveau 3', price : 1000000, income: -1500, ecologie: -1, economie: -1, bienEtre: 20, pop: 0, description: "L'hôpital est un bâtiment coûteux en entretien et polluant mais qui reste obligatoire dans une ville se disant intelligente.\r\n L'hôpital au niveau 3 utilise des techniques modernes de la médecine, plus performantes, économiques et écologiques. Avoir un meilleur hôpital augmente encore plus le bien-être des habitants.",x:0,y:0,sizeX:2,sizeY:2, popMin: 1300},
	{id: 5,name : "poste3", nom:'Poste niveau 3', price: 1000000, income: -1500, ecologie: -1, economie: -1, bienEtre: 20, pop: 0, description: "La poste est un bâtiment peu coûteux en entretien et peu polluant qui augmente le bien-être des habitants. \r\n La poste au niveau 3 possède un réseau de communication plus performant, elle numérise aussi le courrier pour que les lettres arrivent plus vite. Ce principe est moins polluant et plus économique car il ne fait pas intervenir de transports.",x:10,y:-110,sizeX:2,sizeY:2, popMin: 1200},
	{id: 6,name	: "centrale_hydraulique3", nom:'Centrale hydraulique niveau 3', price: 3400000, income : -12500, ecologie : 30, economie : -4, bienEtre: -3, pop: 0, description: "La centrale hydraulique est un bâtiment tres coûteux en entretien mais qui permet produire de l'électricité de manière renouvelable, elle améliore donc beaucoup la statistique d'écologie.La centrale hydraulique au niveau 3 utilise des techniques plus optimisées, permttant de produire plus d'électricité à moindre coût, toujours de manière renouvelable.",x:30,y:-140,sizeX:2,sizeY:2, popMin: 1500},
	{id: 7,name : "panneau_solaire3", nom:'Panneau solaire niveau 3', price: 1200000, income: -500, ecologie: 30, economie: -1, bienEtre: 0, pop: 0, description: "Les panneaux solaires sont assez coûteux en entretien mais permettent de produire de l'électricité de manière renouvelable. ",x: 10, y:-110,sizeX:2,sizeY:2, popMin: 1200},
	{id: 8, name: "parc3", nom:'Parc niveau 3', price: 800000, income: -4000, ecologie: 30, economie: -4, bienEtre: 30, pop: 0, description: "Un parc apporte du bien-être et du divertissement à la population, et permet à la ville de respirer favorisant l'écologie. \r\n Les parcs au niveau 3 ont des espaces verts plus grands, avec plus de poubelles et d'arbres augmentant ainsi le bien-être des habitants et l'écologie.",x: 0, y:-150,sizeX:2,sizeY:2, popMin: 1000},
	{id: 9, name: "usine_recyclage3", nom:'Usine de recyclage niveau 3', price: 2800000, income: -11500, ecologie: 40, economie: -5, bienEtre: -3, pop: 0, description: "Une usine de recyclage est un bâtiment très coûteux en entretien mais qui permet de recycler les déchets de la ville. \r\n L'usine de recylcage au niveau 3 est plus optimisée, permettant de recylcer plus de déchets par jour à moindre coût.",x:10,y:-110,sizeX:2,sizeY:2, popMin: 2000},
	{id: 10, name: "banque3", nom:'Banque niveau 3', price: 3600000, income: 170000, ecologie: -4, economie: 40, bienEtre: 14, pop: 0, description: "La banque est un bâtiment coûteux en entretien, mais essentiel quelque soit la ville car elle permet d'augmenter grandement son économie. \r\n La banque au niveau 3 utilise des intelligences artificielles pour faciliter la demande client, permettant de faire plus de transactions. La sécurité y est aussi fortement augmentée.",x:-200,y:-200,sizeX:2,sizeY:2, popMin: 1200},
	{id: 11, name: "magasin3", nom:'Magasin niveau 3', price: 800000, income: 70000, ecologie: -3, economie: 30, bienEtre: 16, pop: 0, description: "Les magasins permettent à la ville de faire vivre son économie. C'est un peu la base du commerce de chaque ville. \r\n Les magasins au niveau 3 possèdent des sites de vente en ligne, facilitant le commerce et augmentant le bien-être des habitants.",x:10,y:-110,sizeX:2,sizeY:2, popMin: 1200},
	{id: 12, name: "usine3", nom:'Usine niveau 3', price: 2000000, income: 2000000, ecologie: -10, economie: 35, bienEtre: -4, pop: 0, description: "L'usine est un bâtiment très polluant et bruyant, mais qui contribue énormément à l'économie de la ville et rapporte beaucoup. \r\n Les usines au niveau 3 utilisent des procédés modernes, bien moins polluants et plus rapides, augmentant ainsi l'économie et les revenus et ayant un impact moindre sur l'écologie.",x:10,y:-180,sizeX:2,sizeY:2, popMin: 1500},
	{id: 13, name: "mairie3", nom:'Mairie niveau 3', price: 5000000, income: 0, ecologie: 0, economie: 0, bienEtre: 0, pop: 0, description: "La mairie est le bâtiment à partir duquel vous allez pouvoir acheter des avancées technologiques. \r\n La mairie au niveau 3 permet de débloquer les améliorations des autres bâtiments et des technologies de rang 3.",x:0,y:-300,sizeX:2,sizeY:2, popMin: 1500},
	{id: 14, name: "maison3", nom:'Maison niveau 3', price: 800000, income: 20000, ecologie: -2, economie: 10, bienEtre: 10, pop: 500, description: "Les maisons sont essentielles pour avoir des habitants dans la ville. Elles demandent un petit coût en entretien et consomment un peu. \r\n Les maisons de niveau 3 utilisent le principe de la domotique, permettant de tout rendre connecté et plus facile d'accès dans la maison, augmentant le bien-être. Elles sont plus grandes, permettant donc d'acceuillir beaucoup plus de personnes.",x:0,y:-350,sizeX:2,sizeY:2, popMin: 0}
];

let technologieT1 = [
	{id: 0, name: "feuMalvoyant", nom: "Feu Tricolore Malvoyant", price: 250000, ecologie: 0, economie: 0, bienEtre: 3, description: "Installe des feux tricolores pour les malvoyants dans la ville, augmentant le bien-être et la condition de vie des habitants."},
	{id: 1, name: "spotwifi", nom: "Spot Wifi", price: 200000, ecologie: 0, economie: 0, bienEtre: 3, description: "Installation de spot wifi dans toute la ville permettant une connexion aisée à tout moment,augmentant le bien-être et la condition de vie des habitants."},
	{id: 2, name: "feuSmart", nom: "Feu Intelligent", price: 350000, ecologie: 0, economie: 0, bienEtre: 3, description: "Passe le feu au vert quand un véhicule de secours passe, améliorant les soins et la prise en charge lorsqu'il y a des urgences."},
	{id: 3, name: "peageVehiVert", nom: "Péage gratuit pour véhicule vert", price: 400000, ecologie: 3, economie: 0, bienEtre: 0, description: "Place des péages gratuits pour les véhicules verts, incitant les habitants à utiliser des véhicules verts, ce qui augmente donc la statistique d'écologie."},
	{id: 4, name: "e_Admin", nom: "e-administration", price: 300000, ecologie: 0, economie: 3, bienEtre: 3, description: "Application permettant de faire toutes les démarches administratives en ligne, accélerant donc l'économie et améliorant le bien-être des habitants."},
	{id: 5, name: "dechetIntell", nom: "Système de gestion des déchets intelligents", price: 250000, ecologie: 3, economie: 0, bienEtre: 0, description: "Permet de trier les déchets de manière plus efficace et plus rapide."},
	{id: 6, name: "passageCamions", nom: "Passage des camions", price: 500000, ecologie: 3, economie: 0, bienEtre: 0, description: "Optimisation du passage des camions réduisant les émissions de CO2."},
	{id: 7, name: "capteurPoub", nom: "Capteur poubelle", price: 250000, ecologie: 3, economie: 0, bienEtre: 0, description: "Capteur qui indique si une poubelle est remplie ou non, accélerant et améliorant le recyclage des déchets."},
	{id: 8, name: "LED", nom: "Lampadaire LED", price: 200000, ecologie: 0, economie: 3, bienEtre: 0, description: "Installation de lampadaires LED qui consomment moins d'énergie et sont donc moins coûteux."}
];

let technologieT2 = [
	{id: 0, name: "voitureElec", nom: "Voiture électrique", price: 500000, ecologie: 0, economie: 5, bienEtre: 0, description: "Utilisation de voitures électriques qui sont moins polluantes, améliorant donc l'écologie."},
	{id: 1, name: "routeElec", nom: "Route qui recharge la batterie", price: 700000, ecologie: 0, economie: 0, bienEtre: 7, description: "Routes qui rechargent la batterie des voitures électriques, permettant une meilleure autonomie et donc un meilleur confort de vie."},
	{id: 2, name: "parkingSmart", nom: "Parking intelligent", price: 600000, ecologie: 0, economie: 0, bienEtre: 6, description: "Installe des capteurs sur les parkings ce qui donne les places libres grâce à une application."},
	{id: 3, name: "bornes", nom: "Bornes connectées ", price: 450000, ecologie: 0, economie: 0, bienEtre: 6, description: "Installe des bornes connectées dans la ville, permettant de guider les touristes grâce à une carte interactive."},
	{id: 4, name: "compacPoub", nom: "Compacteur poubelle", price: 250000, ecologie: 6, economie: 0, bienEtre: 0, description: "Installe des compacteurs sur les poubelles pour augmenter la capacité de stockage des déchets."},
	{id: 5, name: "IA_Trie", nom: "IA tri", price: 350000, ecologie: 6, economie: 0, bienEtre: 0, description: "Utilise une IA permettant de faciliter et d'améliorer davantage le tri des déchets."},
	{id: 6, name: "capteurMouv", nom: "Capteur de mouvement lampadaire", price: 300000, ecologie: 2, economie: 0, bienEtre: 4, description: "Installe des capteurs de mouvement dans la rue, ce qui permet de détecter la présence d'une personne la nuit pour allumer ou non un lampadaire."}
];

let technologieT3 = [
	{id: 0, name: "voitureAuto", nom: "Voiture autonome", price: 1000000, ecologie: 0, economie: 0, bienEtre: 8, description: "Permet d'avoir des voitures capables d'aller à un point A à B sans conducteur, améliorant le confort de vie des habitants"},
	{id: 1, name: "IAPolice", nom: "Robot policier", price: 13000000, ecologie: 0, economie: 0, bienEtre: 7, description: "IA capable d'intéragir avec des personnes, peut localiser le danger et contacter les secours et intervenir en cas de danger, ce qui donne un sentiement de sécurité aux habitants."},
	{id: 2, name: "tuyauDech", nom: "Réseau de tuyaux souterrains pour déchets", price: 900000, ecologie: 6, economie: 2, bienEtre: 0, description: "Crée un réseau de tuyaux souterrains, ce qui optimise la gestion des déchets."},
	{id: 3, name: "IAClean", nom: "Robot nettoyeur", price: 11000000, ecologie: 11, economie: 0, bienEtre: 0, description: "Permet d'avoir des robots pour nettoyer les rues, faisant baisser la pollution."},
	{id: 4, name: "capteurRes", nom: "Capteur sur les réseaux électriques, hydroliques", price: 1000000, ecologie: 3, economie: 7, bienEtre: 0, description: "Installe des capteurs permettant de détecter les problèmes de fuites d'eau et autres problèmes, permettant de réduire les pertes d'énergie et d'eau."},
	{id: 5, name: "intelOpe", nom: "Intelligent operation center ", price: 16000000, ecologie: 0, economie: 3, bienEtre: 8, description: "Visualisation de toutes les données, big data en temps réel de la ville."}	
];